spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=demo
spring.datasource.password=demo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.docker.compose.enabled=true

jwt.secret=TjzrkHV/nupt9bKCIeLy3HqXHr/6GIdtFhdJPU8Mqek=
jwt.expiration-ms=36000000